### ISSUE TITLE
BUG: Collab avatars sometimes don't match the artist

### ISSUE THREAD

**Issue by ciphrd** [fxhash/fxhash-website#105]
Reproduce:
* open project page authored by multiple artists
* refresh
Sometimes the avatars don't match the artist

![image](https://user-images.githubusercontent.com/18054507/166890695-d8c18f7d-7b6e-4c4b-87bd-a11bcc79ad27.png)
![image](https://user-images.githubusercontent.com/18054507/166890768-d5c7e8d0-ccd3-4fdc-9c1b-d04d7e9a0067.png)

We sometimes randomize the order of the artists in a collaboration, this is most likely the root cause of this issue.

**Comment by GemN** [comment]
on it. 
(probably an hydratation problem)
