### ISSUE TITLE
Factorize the sort and filter options

### ISSUE THREAD

**Issue by ciphrd** [fxhash/fxhash-website#107]
The same strategy is used on the `CardExplorer` components for the implementation of the filters and sort options. Moreover, the API implements the same api to sort & filter a query, so we can factorize this as suggested by @GemN 

This factorization should abstract as much features as possible, that's why I'm proposing the implementation of a generic `ExploreSettings` interface we will inherit for every different `CardExplorer` sort & filters definitions. This is a rough example of what I have in mind:

```ts
interface IExploreParameters {
  sortOptions: IOptions[]
  filterTags: (filters) => ExploreTagDef[]
  // we can probably factorize more into this interface, it's just to have an idea
}
```

Requires:
* https://github.com/fxhash/fxhash-website/issues/82
* https://github.com/fxhash/fxhash-website/issues/88
* https://github.com/fxhash/fxhash-website/issues/89

To start the refacto from a clean state

**Comment by CiaccoDavide** [comment]
I think I can tackle this one

**Comment by CiaccoDavide** [comment]
@ciphrd were you thinking about something like this?
https://github.com/fxhash/fxhash-website/commits/dev/src/utils/filters.ts

or something even more "refactored"?

I just used @GemN refactor from `filters.ts` and extended it to include the unrefactored `filterTags` from `Marketplace` and `UserCollection` card explorers...

here: #136

**Comment by CiaccoDavide** [comment]
> I can continue from here if you want

Hi @GemN! Sure, you can pick this up, I really didn't do much 😉

**Comment by liamegan** [comment]
Status on this @GemN

**Comment by maerzhase** [comment]
most done more will happen on the fly
