### ISSUE TITLE
Activity infinite loader looks bad and should be replaced by placeholder components

### ISSUE THREAD

**Issue by ciphrd** [fxhash/fxhash-website#110]
Currently there's this ugly loader overlapping with the Actions when Activity feed is loading:

![image](https://user-images.githubusercontent.com/18054507/166924975-841e91fa-f486-4413-ad4d-641e3fdb648c.png)

We would like to replace this with an optimistic UI (sorry for the Paint sketch):

![image](https://user-images.githubusercontent.com/18054507/166925312-3a1b3104-3204-49a0-9e60-135d12abc967.png)

You can reuse the `.placeholder` class in `Effects.module.scss` to achieve the gradient loader effect.

**Comment by GemN** [comment]
on it
