### ISSUE TITLE
Timezones without round offsets are not displayed properly on the schedule

### ISSUE THREAD

**Issue by ciphrd** [fxhash/fxhash-website#112]
This one is tricky.

When I originally designed the schedule I didn't know that some timezones had some real offsets (for instance Caracas is UTC-4:30).
The current schedule uses squares for every hour:

![image](https://user-images.githubusercontent.com/18054507/166926842-9c8567f9-a997-4e65-beeb-df21fdc834ec.png)

But in the case of those non-integer offsets, it doesn't display properly.

Current behavior:

![image](https://user-images.githubusercontent.com/18054507/166926964-69efcda8-a463-40e5-8293-c01e10d4a8df.png)

Expected behavior (in dark blue):

![image](https://user-images.githubusercontent.com/18054507/166927207-ebcd40ed-dca7-480c-b5ad-eeee1f2482fd.png)

It requires some rework on the `Schedule` component and its rendering logic.

**Comment by GemN** [comment]
on it
