### ISSUE TITLE
[UX] Add an empty message when there is no creations in user profile

### ISSUE THREAD

**Issue by GemN** [fxhash/fxhash-website#115]
When the user has no creations, there is just a blank space. I think we should display at least an empty message (ex: "'username' has not made any creations yet, come back later!").

Currently can be confusing to see nothing (can make you think of an error while loading data)

Reference: https://www.fxhash.xyz/u/NukCZ

![Capture d’écran 2022-05-05 à 18 18 18](https://user-images.githubusercontent.com/13420650/166977839-dac1de85-9d3b-4f87-9058-527ef89f8e9d.png)

**Comment by GemN** [comment]
@maerzhase I just reported this as an issue but it was not validated by @ciphrd
Maybe I should add a flair label "suggestion" until it's validated ?

**Comment by maerzhase** [comment]
sure! sounds like good idea! in general i agree with your issue description. there should be some message handling the empty view

**Comment by ciphrd** [comment]
Good spot. Let's add this
