### ISSUE TITLE
Replace user activity by user dashboard

### ISSUE THREAD

**Issue by ciphrd** [fxhash/fxhash-website#122]
We want to replace the `activity` tab in the user profile by a more generic-purpose dashboard in which we'll centralize a few features to make it easier for users to inspect their activity as well as the activity of other users.

Here's a design for the implementation of the first iteration of the dashboard feature:

![Dashboard (1)](https://user-images.githubusercontent.com/18054507/167464005-4f58ca1d-cf8f-4337-acf0-fc521a4fb32f.jpg)

The first iteration of the dashboard will only have a `sales` table in which we will put the user sales on the secondary market, either as the direct seller or as the author of a piece. The sales endpoint will cover all these cases.

- [ ] replace `activity` tab by `dashboard` tab (and update the URL too)
- [ ] create a 301 redirection from `activity` to `dashboard` url in the `next.config.js` file
- [ ] the current activity infinite scroll should be moved at the bottom of the page
- [ ] call the `user { sales }` endpoint to query the sales and display the sales in the table
- [ ] handle responsiveness of the table

Here's some implementation details layered on top of the design:

![Dashboard (2)](https://user-images.githubusercontent.com/18054507/167464696-72a7cd3a-1f5d-44ae-b176-287ce52ed081.jpg)

For the implementation of this feature, the API will need the `sales` field in the `user` to be implemented:

* https://github.com/fxhash/fxhash-api/issues/18

**Comment by GemN** [comment]
@ciphrd I need a way to manipulate ```user { sales }```
- filter by type in [LISTING_V1_ACCEPTED, LISTING_V2_ACCEPTED]
- sort by createdAt-desc
