### ISSUE TITLE
Add the size select to the `/explore`, `/incoming`, `/marketplace`, `/marketplace/generative/{id}` pages

### ISSUE THREAD

**Issue by ciphrd** [fxhash/fxhash-website#130]
Add the size select component to the given pages

![image](https://user-images.githubusercontent.com/18054507/167925368-4b170370-2ef1-413d-997d-34fde194c29f.png)

Because we have 2 resolutions available, we need to make sure that if the size is set to big on these pages, the HQ image is used instead of the LQ one.

- [x] `/explore`
- [x] `/incoming`
- [x] `/marketplace`
- [x] `/marketplace/generative/{id}`
- [x] use the HQ preview if the size is set to big

`/explore` and `/incoming` should have the same scope-identifier.

@maerzhase maybe you'll want to take this one since you've been working on this feature.

**Comment by maerzhase** [comment]
sure! will take care of it!

**Comment by liamegan** [comment]
@maerzhase did this get done?

**Comment by maerzhase** [comment]
PR is open since a while I will resolve the merge conflicts then its read for review
