### ISSUE TITLE
Tooltip in UserHeader clipped

### ISSUE THREAD

**Issue by maerzhase** [fxhash/fxhash-website#179]
The Tooltip in the UserHeader is currently clipping because of the overflow: hidden 

<img width="1041" alt="Screenshot 2022-06-01 at 17 43 17" src="https://user-images.githubusercontent.com/1128485/171445213-702c711e-8708-43bf-a4c8-929c982f29c7.png">

@GemN this was introduced as a fix for mobile maybe we should only add this style on smaller breakpoints?

**Comment by GemN** [comment]
Thought overflow-x would to the trick for that component, but I moved it to the main wrapper so that any content that overflow doesnt destroy layout
