### ISSUE TITLE
Page to view an article

### ISSUE THREAD

**Issue by ciphrd** [fxhash/fxhash-website#192]
PR branch target: `feature/articles`

Create a page to view an article. The page can be accessed using these 2 urls:

- `/article/[slug]`: slug is the unique string identifier for the article, articles can be queried by slug on the DB
- `/article/id/[id]`: article by ID

![Image](https://user-images.githubusercontent.com/18054507/173651023-549115b2-5e24-41bd-a097-90ab7d543443.png)

The `RELATED ARTICLES` section will be implemented in a different PR.

**Comment by GemN** [comment]
I'm creating a branch from #204 to not overwrite my types
