### ISSUE TITLE
Responsive pass

### ISSUE THREAD

**Issue by ciphrd** [fxhash/fxhash-website#20]
Many pages of the website don't display properly on mobile.

* Some generic rules such as the font size must be redefined on smaller screens so that big texts don't take the whole screen.
* A pass on the most common modules (header, footer, navigation) as well as a pass on all the pages is necessary.

![image](https://user-images.githubusercontent.com/18054507/148442720-6771e8b8-27d7-4e24-b806-93c696addb2b.png)
![image](https://user-images.githubusercontent.com/18054507/148442756-52734459-fb69-4ebb-b86c-93df4d4cdd25.png)
![image](https://user-images.githubusercontent.com/18054507/148442810-e0e3bd92-5042-46cf-8062-0e0fec2a835c.png)

**Comment by ciphrd** [comment]
_Note: The issue was written a while ago so some screens are outdated, but a responsive pass is still needed._

**Comment by GemN** [comment]
on it
