### ISSUE TITLE
Add a new `GenTokLabel`: `Includes prerendered components`. This would provide nuance to the existing label of `Image Composition` which currently doesn't exist.

### ISSUE THREAD

**Issue by liamegan** [fxhash/fxhash-website#240]

**Comment by ciphrd** [comment]
Nice way to put it, `Image Composition` is indeed a bit vague.

As we are aiming for the best terminology, I have a 2 concerns with this one:
- prerendered -> a little bit ambiguous, as for instance drawings don't seem to be in this category
- components -> element  (i feel like element is a little bit more generic, not sure though)

**Comment by ToastedJelly** [comment]
Is the goal to replace `Image Composition` or just add a label for everything else that isn't Images like 3D models, Sound etc?
How does `Asset Composition` sound?

**Comment by liamegan** [comment]
It won't replace image composition, as that's an important category of its own. "Asset composition" removes some of the flexibility of this category in that it speaks mostly to non-code assets, which people might not associate with, for example, SVG files.

**Comment by liamegan** [comment]
I would very much like this as soon as possible to deal with things like this https://www.fxhash.xyz/generative/slug/the-human-figure-in-motion
