### ISSUE TITLE
Add NSFW toggle to Settings menu. This will filter out content that contains the labels `Sexual content` and `Sensitive content`.

### ISSUE THREAD

**Issue by liamegan** [fxhash/fxhash-website#266]
![Image](https://user-images.githubusercontent.com/627944/181119246-af93ca01-15d5-4271-b8b8-8641e744dd1f.png)

**Comment by ciphrd** [comment]
We need a design for:

- [ ] every token card to have an overlay (maybe blur?) and a warning
- [ ] a toggeable overlay over the artwork frame 

This feature should also:

- force image display on NSFW tokens if setting is set on "show live version" by default

**Comment by ciphrd** [comment]
* Referencing #267 

There's some overlap in the implementation, imo both should be implemented by the same PR

**Comment by liamegan** [comment]
Added a forum post about both.

**Comment by liamegan** [comment]
Toggle should be `off` by default.

Design for this
https://discord.com/channels/900333075509149767/1024339987577192519/1024412811046158336

![image](https://user-images.githubusercontent.com/627944/192629475-653190b7-5e6b-44f6-be9b-9b02ab9d5843.png)

> Content warning:
> Nudity, violence, and sensitive content
