### ISSUE TITLE
Add Epilepsy toggle to settings menu. When checked it should hide tokens that contain the label `Epileptic trigger.`

### ISSUE THREAD

**Issue by liamegan** [fxhash/fxhash-website#267]
![Image](https://user-images.githubusercontent.com/627944/181119677-7a64895a-8706-48c6-9067-c32676076751.png)

**Comment by ciphrd** [comment]
We need a design for:

- [ ] every token card to have an overlay (maybe blur?) and a warning
- [ ] a warning which displays over the iframe when played

This feature should also:

- force image display on epileptic trigger tokens if setting is set on "show live version" by default

**Comment by ciphrd** [comment]
* Referencing #266 

Both should be implemented by the same PR

**Comment by liamegan** [comment]
We should make photosensitive toggle on by default if the user's browser is set to `prefersReducedMotion`

**Comment by liamegan** [comment]
Design for this
https://discord.com/channels/900333075509149767/1024339987577192519/1024412811046158336

![image](https://user-images.githubusercontent.com/627944/192629475-653190b7-5e6b-44f6-be9b-9b02ab9d5843.png)

> Photosensitive warning:
> This gentk contains flashes or light that could trigger seizures for people with visual sensitivities.
