### ISSUE TITLE
Update allow list controls in token edit page to contain overflow to the container and scroll internally. Currently it extends off the page and hides the submit button.

### ISSUE THREAD

**Issue by liamegan** [fxhash/fxhash-website#271]
![Image](https://user-images.githubusercontent.com/627944/181120263-a63c978e-92e0-4e67-902e-15d9fc509bd1.png)

**Comment by liamegan** [comment]
Users currently have to hack the CSS in inspector in order to submit the changes.

**Comment by GemN** [comment]
fix with #344
