### ISSUE TITLE
[Article editor] Pressing `ENTER` at the end of a heading should create a paragraph

### ISSUE THREAD

**Issue by ciphrd** [fxhash/fxhash-website#279]
* PR target: `feature/articles`

Right now, when we press `ENTER` at the end of a title it create another title block above which rom a UX standpoint, is not good.

**Comment by Anaglyph-ic** [comment]
Changing blocks on Enter is very counter-intuitive to me. Could be just unfocus or validation. But creating a new block on newline can be UX hell for some users.

**Comment by GemN** [comment]
> imo we should stick to best practice of txt editors and I think its normal to create new parapgraph on newline. softlinebreaks allows newline within same block.

To extends your answer, with Google doc, Notion, Medium:
- all of them after a Heading, pressing **Enter** create a new paragraph block.
- If you want to stay in the same paragraph / block, then a soft break is required (typically **SHIFT + ENTER**)

The best UX is to keep the UX users are used to

**Comment by Anaglyph-ic** [comment]
Sure, but that's not your current behaviour. You're not creating a new paragraph, you're creating a new "whatever you just used".  Why would I systematically want to add another title/gentk/spotify link? 

So one solution is making all new blocks paragraph by default. If not, just unfocus the current block and let the user create whatever block they need?

**Comment by GemN** [comment]
> Sure, but that's not your current behaviour. You're not creating a new paragraph, you're creating a new "whatever you just used". Why would I systematically want to add another title/gentk/spotify link?
> 
> So one solution is making all new blocks paragraph by default. If not, just unfocus the current block and let the user create whatever block they need?

The editor is a work in progress, the V.1 is not yet finalised (you can see the milestone not completed), the current behavior is not the final behavior hence this github issue. 

We specifically did this issue to add a paragraph after creating a new block on Enter, we never wanted to keep a new "whatever you just used" block.
