### ISSUE TITLE
[Article editor] Slate to markdown introduces a weird html comment between 2 list blocks

### ISSUE THREAD

**Issue by ciphrd** [fxhash/fxhash-website#296]
* base branch: `feature/articles`

It's a very odd behavior.
When adding 2 lists one after the other, the parser adds this weird comment between the 2 list blocks ?!:

![image](https://user-images.githubusercontent.com/18054507/181826305-f7ba6e57-f6bd-4d04-86c6-bd45eb67befb.png)

It only happens when we add 2 lists next to each other, weird af.

**Comment by maerzhase** [comment]
I found this stackoverflow posts which describes the comment between list as one possible desired behaviour to not concatenate the lists: https://stackoverflow.com/questions/23821014/markdown-having-multiple-lists

**Comment by maerzhase** [comment]
@ciphrd this behaviour seems intended and comes from the remark plugin `mdast-util-to-markdown`: 

> When two unordered lists appear next to each other: * a\n- b. CommonMark sees different bullets as different lists, but several markdown parsers parse it as one list. To solve for both, we instead inject an empty comment between the two lists: * a\n\n* b, but if bulletOther is given explicitly, it will be used instead

https://github.com/syntax-tree/mdast-util-to-markdown#optionsbulletother
