### ISSUE TITLE
Changing <iframe> url pushes a new URL to the browser stack

### ISSUE THREAD

**Issue by ciphrd** [fxhash/fxhash-website#31]
When on a token page, if we hit the `variations` button a few times, we can only get back to the previous page by hitting the previous button as many times as we clicked on `variations`.

This is actually the expected behavior from browser specs, but is not very good from a UX perspective.

This is classified as a bug, but it truly isn't. We just need to find a workaround.

**Comment by CiaccoDavide** [comment]
I can do this one!

**Comment by CiaccoDavide** [comment]
solved by #103

**Comment by CiaccoDavide** [comment]
This only applies to the gentk pages, not when using the sandbox or during the minting process (while testing/changing hashes manually)

**Comment by ciphrd** [comment]
Fine for the sandbox :)
Closing as you resolved the issue.
