### ISSUE TITLE
Articles don't appear in the mobile main menu 

### ISSUE THREAD

**Issue by Anaglyph-ic** [fxhash/fxhash-website#322]
Triggering responsive mode doesn't load the same menu, articles are not visible. This might be a WIP, I'm opening this issue just in case you don't have this one on your radar yet.

<img width="581" alt="" src="https://user-images.githubusercontent.com/97275120/183290232-4c97b86e-5976-457c-80ca-f65550c21864.png">

**Comment by GemN** [comment]
Like on desktop, articles are under the profile dropdown

**Comment by Anaglyph-ic** [comment]
Indeed! Maybe it would make sense to put them in the main menu? To make them easier to find to the unsynced?
