### ISSUE TITLE
[Articles] Body text area - Adding a quote block and refreshing results in double controls

### ISSUE THREAD

**Issue by liamegan** [fxhash/fxhash-website#328]
Repro:
1. Add a quote block
2. add text
3. refresh

Notice double add/edit controls

![image](https://user-images.githubusercontent.com/627944/183948050-59542b30-3cbf-46ad-abe0-e02bc6c96981.png)

It looks like this is because, upon refresh, block controls are added internally to the quote blocks. This might be expected, but oddly this behaviour changes on refresh of page vs. initial edit.

**Comment by GemN** [comment]
Linked to #294 
We need to define the blockquote behavior since we are supposed to be able to choose different kind of components within blockquotes. (the later screenshot is the "true" version according to md standards)

**Comment by liamegan** [comment]
Closing as redundant. Thanks.
