### ISSUE TITLE
Articles whose title and contents are only INTs do not appear on dev front

### ISSUE THREAD

**Issue by Anaglyph-ic** [fxhash/fxhash-website#349]
Articles whose title/abstract/contents is only spaceless INTs do not appear on dev front.

Maybe there's something else going on with the dev front? But also maybe titling an article with an INT makes it a "ghost" that never shows up on the front (in which case please keep it and forget about this issue).

**Comment by ciphrd** [comment]
Issue at the indexer level, fixed during the days thx for reporting <3
