### ISSUE TITLE
[Articles] Local Storage object sometimes not created in user agent

### ISSUE THREAD

**Issue by Anaglyph-ic** [fxhash/fxhash-website#374]
User explained on the discord not having anything saved. Upon exploration (through screenshots), they indeed do not have a `local_articles` entry in their LocalStorage.

User is using chrome on a MPB.

Version 105.0.5195.102 (Official Build) (arm64)

Doesn't seem to have any specific privacy extensions, and beacon entries seem to be created normally.

**Comment by maerzhase** [comment]
While it will be very hard to reproduce and find the cause of this issue, we could show an alert when people try to close the tab with unsaved changes as we do it with media items that are not uploaded to ipfs.

**Comment by Anaglyph-ic** [comment]
You could also have a checker that says "failed to autosave" instead of just not showing "article was saved" (or whatever the tooltip actually says)?
