### ISSUE TITLE
[Responsive] Tabs should be horizontally scrollable if they take too much horizontal space

### ISSUE THREAD

**Issue by ciphrd** [fxhash/fxhash-website#387]
* base branch: `dev`

# Current issue

Tabs on mobile are taking way too much vertical space:

![image](https://user-images.githubusercontent.com/18054507/189535104-ac855b55-b04b-4e46-84f4-fc03134fc097.png)

# Solution

Tabs should be horizontally scrollable if they take too much horizontal space:

![image](https://user-images.githubusercontent.com/18054507/189535123-b7c881af-502a-4cec-aa31-616996e5e631.png)

See figma file:
https://www.figma.com/file/bdCVYIEKTy8lyBLjIDWvQn/Website?node-id=96%3A3323

**Comment by GemN** [comment]
done in #438
