### ISSUE TITLE
Regression: When in dark mode, some text that should be light still appears as dark

### ISSUE THREAD

**Issue by liamegan** [fxhash/fxhash-website#470]
- Go to fxhash website
- Open settings
- Turn on dark mode.

Notice that some text in dialogues and modals appears as black on a dark background, making it unreadable.

![image](https://user-images.githubusercontent.com/627944/200127820-d31db1ed-5e10-4a93-984a-3fcebe27146a.png)
![image](https://user-images.githubusercontent.com/627944/200127834-4b0ce444-2a2d-49df-9bab-8ebd92faa020.png)

**Comment by daniel-bergmann** [comment]
I can help out with that if you need
