### ISSUE TITLE
Keyboard navigation is messed up

### ISSUE THREAD

**Issue by Olaleye-Blessing** [fxhash/fxhash-website#472]
There is no way to work with the settings modal with keyboard. The modal isn't focused after opening the modal, rather, it continues to the search icon.

https://user-images.githubusercontent.com/70102539/200135634-34fc5d8a-2b76-400a-ba95-696c09c4f278.mp4

Notice the outline didn't enter the modal.

**Comment by GemN** [comment]
Self note: Using a portal should move the focus inside the portal to keep keyboard navigation
