### ISSUE TITLE
Sort gentk actions in the correct order

### ISSUE THREAD

**Issue by crypt0biwan** [fxhash/fxhash-website#502]
It would make more sense if this "listing cancel" action was in between the listings itself.
Looks like [they were included in the same "operation group"](https://tzkt.io/ootzcKukgJKNVBovkm6uZ4ZzzCR2McyG5MuRSbns7eMnryv5Rtq/40399276)?

Asset: [Dencity #669](https://www.fxhash.xyz/gentk/757536)

![https://cdn.discordapp.com/attachments/925802776699744256/1048172279890202685/Screenshot_2022-12-02_at_10.26.17.png](https://cdn.discordapp.com/attachments/925802776699744256/1048172279890202685/Screenshot_2022-12-02_at_10.26.17.png)

**Comment by maerzhase** [comment]
i see what you mean. will take a look
