### ISSUE TITLE
Add dates to presskit/media events

### ISSUE THREAD

**Issue by maerzhase** [fxhash/fxhash-website#516]
As suggested by @GemN we need to collect the dates and add them.

https://user-images.githubusercontent.com/13420650/207649356-fd20ee69-b730-45d4-b8e6-d00ce1b65a21.png

# Todo

- [x] Collect dates from team
- [x] Implement dates into section headers

**Comment by qaulv** [comment]
Bright Moments Venice: 06.10.22-07.10.22
Dekabinnet Berlin: 26.07.22 - 05.08.22

Artist Interview Series: Same as Bright Moments 06.10.22-07.10.22 - Full vid released soon (

ABHK: 25.05.22 - 29.05.2022
ABB: 14.06.22-19.06.22
ABP+: 18.10.22-23.10.22
ABMB: 29.11.22-03.12.22

Proof of People: 06.07.22-08.07.22
TezDev Paris: 21.07.22 - 23.07.22
NFC Lisbon: 04.04.22 - 05.04.22

**Comment by maerzhase** [comment]
done on #509
