### ISSUE TITLE
Custom password protection

### ISSUE THREAD

**Issue by ciphrd** [fxhash/fxhash-website#522]
* base branch: `dev`

# Current solution

Right now, we are using vercel's password protection feature, which is not very good:
* a single password for all the preview branches
* 150$ / mo

![image](https://user-images.githubusercontent.com/18054507/209258587-5719bdfc-13a9-45af-81d6-0d3f73f7a069.png)

While it was good, we will now need a more granular approach to secure our preview branches.

# Proposed solution

* Implement a site-wide protection if the following environment variable is defined: `PASSWORD_PROTECTION`. The value of the env variable will be the password required to authenticate.
* The session is preserved with an http-only cookie
* If we change the password, the connection should be invalidated (we can derive a secret string from the password so that when the password is changed, it changes the secret key used to create and parse the user cookie)
* Focus on speed: please find a solution where the least amount of code is executed if PASSWORD_PROTECTION is empty or undefined. Maybe there is a way to set this in the config, or only bundle some code at build time if the env is defined. The takeaway is that the prod environment should not be impacted at all by this.

**Comment by maerzhase** [comment]
https://github.com/instantcommerce/next-password-protect
