### ISSUE TITLE
IPSF upload failed

### ISSUE THREAD

**Issue by DaWe35** [fxhash/fxhash-website#55]
![image](https://user-images.githubusercontent.com/10603822/160479123-05ffa54a-9ecd-41d4-b70f-238f02e3ce5a.png)

![image](https://user-images.githubusercontent.com/10603822/160480192-89e0243a-66eb-40f2-81bd-772413eaa951.png)

Nice error msg btw

**Comment by parallaxrendering** [comment]
Please fix this, I can't upload 1mb file.
I have different error on minting too.

**Comment by ciphrd** [comment]
Fixed with 1.0
