### ISSUE TITLE
Save preferred sorting setting on marketplace generative

### ISSUE THREAD

**Issue by maerzhase** [fxhash/fxhash-website#554]
mentioned by liquid:
> Unrelated, but is it possible to save the filtering used in a project marketplace page during a reload? 
> It always defaults to recently listed but that's rarely useful 😦 

In further discussion we figured we are referring to the sorting settings. 

<img width="1371" alt="Screenshot 2023-01-25 at 19 41 34" src="https://user-images.githubusercontent.com/1128485/214654103-477bfcd1-6606-46be-a82a-c68d4559752d.png">

We should store the setting in  localstorage and also put it in the query params to allow url sharing

https://www.fxhash.xyz/marketplace/generative/24169

**Comment by Jobayer12** [comment]
@maerzhase Please assign me this ticket.
