### ISSUE TITLE
Fix mobile style for mint button with price

### ISSUE THREAD

**Issue by maerzhase** [fxhash/fxhash-website#572]
![image](https://user-images.githubusercontent.com/1128485/218050197-18cb0a9f-61fc-4c57-b188-f26b502958a0.png)

**Comment by alexanderkorytskyi** [comment]
@maerzhase I could do this, but just not clear what is the best way from the design perspective. The most universal solution is to extract a price from the button for screens < 400px. Example:

![image](https://user-images.githubusercontent.com/5627174/221361360-6f41820f-e2b7-46bb-ba3e-695dcedac80d.png)

**Comment by maerzhase** [comment]
fixed
