### ISSUE TITLE
fx(text) in header

### ISSUE THREAD

**Issue by louisholley** [fxhash/fxhash-website#579]
move fx(text) to the header a la
<img width="762" alt="image" src="https://user-images.githubusercontent.com/4563781/220610091-bf55c073-eee7-4830-8005-f0aa265fbc77.png">

- should link [here](https://www.fxhash.xyz/explore/articles)
- the two other links in community can be dropped, feedback goes to an irrelevant site and opening schedule is 24h
- tokens reported link can be moved to the footer?

**Comment by maerzhase** [comment]
done
