### ISSUE TITLE
Filter items by listing status

### ISSUE THREAD

**Issue by shapkarin** [fxhash/fxhash-website#580]
It will be nice to get better filters at `u/{username}/collection` page. For example to filter by listing status:
<img width="343" alt="Screenshot 2023-02-23 at 03 34 57" src="https://user-images.githubusercontent.com/1463086/220809317-5b5a5789-4406-45c0-9cb9-af3e6d4e1c4b.png">

and `activeListing` property can be used to filter

**Comment by donganhxauxi** [comment]
Hi @maerzhase, are you interested in this feature? I would like to work on it.

**Comment by shapkarin** [comment]
`not listed` shows a lot of listed items always
