### ISSUE TITLE
Fix the report() Generative Token contract call not working anymore since contract update

### ISSUE THREAD

**Issue by ciphrd** [fxhash/fxhash-website#60]

**Comment by maerzhase** [comment]
@ciphrd you have some more pinpoints on this one? I'd like to actually pick this one up because I believe it will introduce me to some deeper concepts of the app aside from the frontend features

**Comment by liamegan** [comment]
When you try to use this feature you receive the following error

`[Token ID] Value is not a number: undefined`

![image](https://user-images.githubusercontent.com/627944/191987651-4f33394f-4ae7-4793-b919-a93c13650ae5.png)
