### ISSUE TITLE
Show the reserves bar on the Generative Token card, in the explore page

### ISSUE THREAD

**Issue by ciphrd** [fxhash/fxhash-website#61]

**Comment by CiaccoDavide** [comment]
I can do this one! :)

**Comment by CiaccoDavide** [comment]
@ciphrd 
![image](https://user-images.githubusercontent.com/3226096/165159308-2bbba761-1f90-4a64-98b2-216d2211ed4f.png)

these numbers are the "minted reserves", correct?

(I'm trying to display the reserves progress with the correct width)

**Comment by ciphrd** [comment]
These numbers are the available slots.
You can use the sum of the `amount` field in the reserves of the token

```json
{
  "data": {
    "generativeToken": {
      "reserves": [
        {
          "amount": 12
        },
        {
          "amount": 4
        }
      ],
      "id": 11656
    }
  }
}
```

In this example there are 16 slots left in the reserve

**Comment by CiaccoDavide** [comment]
Thanks! (I understood it shortly after posting the comment 🤦🏼‍♂️)

Is showing the reserve bar enough or should I also display the number of reserves?
![image](https://user-images.githubusercontent.com/3226096/165161658-21b5bd03-daba-4c0a-be93-943f7998e27d.png)

**Comment by CiaccoDavide** [comment]
This is how it shows the amount of reserves (number) without modifying the `MintProgress` component:

![image](https://user-images.githubusercontent.com/3226096/165166118-f50274b6-6e0b-4d47-8510-a407d321c788.png)

but maybe something different like this would be nicer:

![image](https://user-images.githubusercontent.com/3226096/165166431-96757433-e9c1-47bc-a0b1-c901a9bb237c.png)

**Comment by ciphrd** [comment]
2nd option looks better indeed.
3rd option  would be to hide the text and only use the color as a code, which would be the best imo.
What are your thoughts ?

**Comment by CiaccoDavide** [comment]
> What are your thoughts?

I would have left it like it's now (show only the progress bar), while also adding an option in the user preferences settings to show the numerical reserves amount:

![image](https://user-images.githubusercontent.com/3226096/165254032-1cfc8086-a96a-4eed-9cb7-4d640432fe78.png)

but then I remembered that on the right side there's already the price 😅

In the end I think that the best option is to leave it only inside the project page and showing it graphically in the progress bar is good enough...
