### ISSUE TITLE
Scoped setting on the card containers to define the size of the cards in the view

### ISSUE THREAD

**Issue by ciphrd** [fxhash/fxhash-website#63]
Users should be able to define the size of the cards when exploring cards. The setting should be scoped to each page, and persisted on the client-side.

![image](https://user-images.githubusercontent.com/18054507/164909351-81a639dd-c741-4006-9dac-07dd3817c782.png)

It should leverage the existing SettingsContext

The following icon can be used: https://fontawesome.com/icons/square?s=solid

**Comment by maerzhase** [comment]
on it!
