### ISSUE TITLE
Add a `BETA` badge on the beta Generative Tokens (field version = 0)

### ISSUE THREAD

**Issue by ciphrd** [fxhash/fxhash-website#64]

**Comment by maerzhase** [comment]
doing this one

**Comment by maerzhase** [comment]
@ciphrd before i continue. wanted to ask did you had in mind as a badge like "Interactive"  etc. on the cards or should we also include a style in the actual token page? 

### card
<img width="318" alt="Screenshot 2022-05-01 at 11 29 27" src="https://user-images.githubusercontent.com/1128485/166140206-44e4af32-f01f-487a-9512-a36c85c53570.png">

### layout v1
<img width="953" alt="Screenshot 2022-05-01 at 11 30 59" src="https://user-images.githubusercontent.com/1128485/166140225-b5ff6a0b-5852-4d4b-95be-ae66b6820cd8.png">

### layout v2
<img width="889" alt="Screenshot 2022-05-01 at 11 31 32" src="https://user-images.githubusercontent.com/1128485/166140240-7837b26a-bebf-4a6c-b951-8b0b62cc0a64.png">

**Comment by CiaccoDavide** [comment]
Sorry to barge in, but wouldn't be neatier to use a "real" badge for the beta tokens?

I was thinking something like this:

![image](https://user-images.githubusercontent.com/3226096/166220611-25caab70-6eca-4c2e-90a9-605bb1cdecb1.png)
_(profile page / explore)_

![image](https://user-images.githubusercontent.com/3226096/166220682-0d0b6e93-0c34-43cf-830f-cf174a785040.png)
_(marketplace)_

![image](https://user-images.githubusercontent.com/3226096/166220862-aec3775f-e52c-4d93-af38-0ad3ffabbe7b.png)
_(token page)_

![image](https://user-images.githubusercontent.com/3226096/166220877-7c6874fe-0f86-4bc6-a9b8-10df28a76b05.png)
_(listing page)_

**Comment by liamegan** [comment]
Closing this as it has been closed elsewhere.
