### ISSUE TITLE
Notifications are not being cleared when minting multiple times on the same page

### ISSUE THREAD

**Issue by ciphrd** [fxhash/fxhash-website#73]
Reproduce:
* go on a project page
* mint unique iteration, stay on the page
* mint again a new unique iteration

![image](https://user-images.githubusercontent.com/18054507/164977844-3043e1cb-55a6-4045-9afb-709c9642c43b.png)
When done 3 times

This must be a bug with the auto clear in the notification center system

**Comment by Cerfio** [comment]
This one is for me
