### ISSUE TITLE
[Mobile] The filter button should only be displayed the Cards Container is visible

### ISSUE THREAD

**Issue by ciphrd** [fxhash/fxhash-website#83]
We have a `Filters` button which opens the filter panel, displayed at the bottom of the screen on mobile:

![image](https://user-images.githubusercontent.com/18054507/165500436-ea1de01b-b980-4bad-a0a5-0c3d27e92b09.png)

This button should be hidden unless we the Cards Container is in the view. So whenever the red area in the following video is in the view:

https://user-images.githubusercontent.com/18054507/165501909-18296d26-9569-4411-81ba-7902803950a5.mp4

**Comment by GemN** [comment]
on it
