### ISSUE TITLE
Top message banner should be closeable (with client-side persistence)

### ISSUE THREAD

**Issue by ciphrd** [fxhash/fxhash-website#85]
The banner at the top can display a message it gets from the environment variables.

* users should be able to hide this banner by clicking on a cross at the left of the banner

Moreover, we would like to display the banner again if we were to change the value of the message itself:

* persist the `hidden` status based on the message which was hidden
* show the banner if the message was not hidden in the local storage

The current settings context can be used to persist this data on the local storage.

**Comment by maerzhase** [comment]
gonna do that one next :-)
