### ISSUE TITLE
Make the user collection enjoy fetch the whole collection

### ISSUE THREAD

**Issue by ciphrd** [fxhash/fxhash-website#86]
The current enjoy feature of the user collection is fetching the tokens with some pagination, so we can't randomize the order at first.

Instead of using `generativeToken { objkts(skip, take) {} }`, it should use `generativeToken { entireCollection }` instead.

This will require some changes to the component `UserCollectionEnjoy`, feeding the tokens to the `GenerativeEnjoy` component. 

Link to a page:
https://www.fxhash.xyz/u/ciphrd/collection/enjoy

**Comment by maerzhase** [comment]
on it.
