### ISSUE TITLE
DevExperience: do imports via aliases instead of relative paths

### ISSUE THREAD

**Issue by maerzhase** [fxhash/fxhash-website#94]
Not sure if everybody agrees but i'd prefer to use alias imports instead of relative paths... 

Nextjs offers this: https://nextjs.org/docs/advanced-features/module-path-aliases

there is a codemod that we can probaly use to do the refactor: https://github.com/s-yadav/relative-to-alias#aliasing-modules

**Comment by GemN** [comment]
@maerzhase I think you can start with the first alias on one branch and we'll follow - since it's retro compatible we don't need to update all paths
